COMPLAINT_CATEGORY_MAP = {
    "01": "Accident – Construction/Plumbing",
    "03": "Adjacent Buildings - Not Protected",
    "04": "After Hours Work – Illegal",
    "05": "Permit – None (Building/PA/Demo etc.)",
    "06": "Construction – Change Grade/Change Watercourse",
    "09": "Debris – Excessive",
    "10": "Debris/Building - Falling or In Danger of Falling",
    "12": "Demolition - Unsafe/Illegal/Mechanical Demo",
    "13": "Elevator In (FDNY) Readiness - None",
    "14": "Excavation - Undermining Adjacent Building",
    "15": "Fence - None/Inadequate/Illegal",
    "16": "Inadequate Support/Shoring",
    "18": "Material Storage – Unsafe",
    "20": "Landmark Building – Illegal Work",
    "21": "Safety Net/Guardrail - Damaged/Inadequate/None (over 6 Story/75 ft.)",
    "23": "Sidewalk Shed/Supported Scaffold - Inadequate/Defective/None/No Permit",
    "29": "Building – Vacant, Open and Unguarded",
    "30": "Building Shaking/Vibrating/Structural Stability Affected",
    "31": "Certificate of Occupancy – None/Illegal/Contrary to CO",
    "35": "Curb Cut/Driveway/Carport – Illegal",
    "37": "Egress – Locked/Blocked/Improper/No Secondary Means",
    "45": "Illegal Conversion",
    "49": "Storefront or Business Sign/Awning/Marquee/Canopy – Illegal",
    "50": "Sign Falling - Danger/Sign Erection or Display In Progress – Illegal",
    "52": "Sprinkler System – Inadequate",
    "53": "Vent/Exhaust – Illegal/Improper",
    "54": "Wall/Retaining Wall – Bulging/Cracked",
    "55": "Zoning – Non-conforming",
    "56": "Boiler – Fumes/Smoke/Carbon Monoxide",
    "58": "Boiler – Defective/Non-operative/No Permit",
    "59": "Electrical Wiring – Defective/Exposed, In Progress",
    "62": "Elevator - Danger Condition/Shaft Open/Unguarded (Priority A)",
    "63": "Elevator - Danger Condition/Shaft Open/Unguarded (Priority B)",
    "65": "Gas Hook-Up/Piping – Illegal or Defective",
    "66": "Plumbing Work – Illegal/No Permit (Also Sprinkler/Standpipe)",
    "67": "Crane – No Permit/License/Cert/Unsafe/Illegal",
    "71": "SRO – Illegal Work/No Permit/Change In Occupancy Use",
    "73": "Failure to Maintain",
    "74": "Illegal Commercial/Manufacturing Use In Residential Zone",
    "75": "Adult Establishment",
    "76": "Unlicensed/Illegal/Improper Plumbing Work In Progress",
    "77": "Contrary To LL58/87 (Handicap Access)",
    "78": "Privately Owned Public Space/Non-Compliance",
    "79": "Lights from Parking Lot Shining on Building",
    "80": "Elevator Not Inspected/Illegal/No Permit",
    "81": "Elevator – Accident",
    "82": "Boiler – Accident/Explosion",
    "83": "Construction – Contrary/Beyond Approved Plans/Permits",
    "85": "Failure to Retain Water/Improper Drainage (LL103/89)",
    "86": "Work Contrary to Stop Work Order",
    "88": "Safety Net/Guard Rail - Damaged/Inadequate/None (6 fl. 75ft. or less)",
    "89": "Accident – Cranes/Derricks/Suspension",
    "90": "Unlicensed/Illegal Activity",
    "91": "Site Conditions Endangering Workers",
    "92": "Illegal Conversion of Manufacturing/Industrial Space",
    "93": "Request for Retaining Wall Safety Inspection",
    "94": "Plumbing - Defective/Leaking/Not Maintained",
    "1A": "Illegal Conversion Commercial Building/Space to Dwelling Units",
    "1B": "Illegal Tree Removal/Topo. Change In SNAD",
    "1D": "Con Edison Referral",
    "1E": "Suspended (Hanging) Scaffolds - No Permit/License/Dangerous/Accident",
    "1G": "Stalled Construction Site",
    "1K": "Bowstring Truss Tracking Complaint",
    "1Z": "Enforcement Work Order (DOB)",
    "2A": "Posted Notice or Order Removed/Tampered With",
    "2B": "Failure to Comply with Vacate Order",
    "2C": "Smoking Ban – Smoking on Construction Site",
    "2D": "Smoking Signs – No Smoking Signs Not Observed on Construction Site",
    "2E": "Demolition Notification Received",
    "2F": "Building Under Structural Monitoring",
    "2G": "Advertising Sign/Billboard/Posters/Flexible Fabric – Illegal",
    "2H": "Second Avenue Subway Construction",
    "2J": "Sandy: Building Destroyed",
    "2K": "Structurally Compromised Building (LL33/08)",
    "2L": "Façade (LL11/98) – Unsafe Notification",
    "2M": "Monopole Tracking Complaint",
    "3A": "Unlicensed/Illegal/Improper Electrical Work In Progress",
    "4A": "Illegal Hotel Rooms In Residential Buildings",
    "4B": "SEP – Professional Certification Compliance Audit",
    "4C": "Excavation Tracking Complaint",
    "4D": "Interior Demo Tracking Complaint",
    "4F": "SST Tracking Complaint",
    "4G": "Illegal Conversion No Access Follow-Up",
    "4J": "M.A.R.C.H. Program (Interagency)",
    "4K": "CSC – DM Tracking Complaint",
    "4L": "CSC – High-Rise Tracking Complaint",
    "4M": "CSC – Low-Rise Tracking Complaint",
    "4N": "Retaining Wall Tracking Complaint",
    "4P": "Legal/Padlock Tracking Complaint",
    "4W": "Woodside Settlement Project",
    "5A": "Request for Joint FDNY/DOB Inspection",
    "5B": "Non-Compliance with Lightweight Materials",
    "5C": "Structural Stability Impacted – New Building Under Construction",
    "5E": "Amusement Ride Accident/Incident",
    "5F": "Compliance Inspection",
    "5G": "Unlicensed/Illegal/Improper Work In Progress",
    "6A": "Vesting Inspection",
}
